development:
  adapter: postgresql
  encoding: 'utf8'
  database: project_todo
  pool: 5
  host: localhost
  username: postgres
  password: postgres
  port: 5432

production:
  adapter: postgresql
  encoding: 'utf8'
  database: project_todo
  pool: 5
  host: localhost
  username: postgres
  password: postgres
  port: 5432
 
